sonar.projectKey=pronolol
sonar.projectName=pronolol

sonar.exclusions=**/generated/**,**/node_modules/**,**/dist/**,**/build/**
sonar.coverage.exclusions=**/generated/**,**/node_modules/**,**/dist/**,**/build/**,**/test/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.cpd.exclusions=**/generated/**
